#!/usr/bin/env node
/**
 * Assemble supabase/schema.sql from the parts in supabase/schema/.
 *
 * The parts are the source of truth; schema.sql is what you paste into the
 * Supabase SQL editor. Keeping one runnable file matters - the alternative is
 * remembering to paste eleven files in the right order, and the order is the
 * whole point: bookings references members, the functions reference both.
 *
 * Run `npm run schema` after editing a part. `npm run schema -- --check`
 * verifies the file is current without writing, which is what CI does.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const partsDir = join(root, "supabase", "schema");
const target = join(root, "supabase", "schema.sql");

const HEADER = `-- BX Fitness Hub - the whole database, in one file.
--
-- You only need this if you are deploying somewhere serverless, or running
-- more than one instance. On a single server the built-in SQLite store is
-- enough and needs no setup at all (see src/lib/store/sqlite.ts).
--
-- Run this once in the Supabase SQL editor, then set SUPABASE_URL and
-- SUPABASE_SERVICE_ROLE_KEY. The app switches over on its own. Running it
-- again is safe: every statement here is written to be repeatable.
--
-- DO NOT EDIT THIS FILE. It is assembled from supabase/schema/*.sql by
-- scripts/build-schema.mjs - edit the part you mean and run \`npm run schema\`.
`;

/** The parts, in the order they have to run. The filenames carry the order. */
export function partFiles() {
  return readdirSync(partsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();
}

export function buildSchema() {
  const sections = partFiles().map((file) => {
    const body = readFileSync(join(partsDir, file), "utf8").trimEnd();
    const rule = "-".repeat(75);
    return `-- ${rule}\n-- ${file}\n-- ${rule}\n\n${body}\n`;
  });
  return `${HEADER}\n${sections.join("\n")}`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const built = buildSchema();
  const check = process.argv.includes("--check");

  if (check) {
    const current = readFileSync(target, "utf8");
    if (current !== built) {
      console.error(
        "supabase/schema.sql is out of date with supabase/schema/*.sql.\n" +
          "Run `npm run schema` and commit the result.",
      );
      process.exit(1);
    }
    console.log(`supabase/schema.sql is current (${partFiles().length} parts).`);
  } else {
    writeFileSync(target, built);
    console.log(`Wrote supabase/schema.sql from ${partFiles().length} parts.`);
  }
}
